import sys
from dataclasses import dataclass
from typing import Optional

# seq_dict = {"601":"CTGGAGAATCCCGGTGCCGAGGCCGCTCAATTGGTCGTAGACAGCTCTAGCACCGCTTAAACGCACGTACGCGCTGTCCCCCGCGTTTTAACCGCCAAGGGGATTACTCCCTAGTCTCCAGGCACGTGTCAGATATATACATCCTGT"}


seq_dict = {"601":      "CTGGAGAATCCCGGTGCCGAGGCCGCTCAATTGGTCGTAGACAGCTCTAGCACCGCTTAAACGCACGTACGCGCTGTCCCCCGCGTTTTAACCGCCAAGGGGATTACTCCCTAGTCTCCAGGCACGTGTCAGATATATACATCCTGT", 
            "601RTA":   "CTGGAGAATCCCGGTGCCGAGGCCGCTCAATTGGTCGTAGACAGCTCTAGCACCGCTTAAACGCACGTACGCGCTGTCTACCGCGTTTTAACCGCCAATAGGATTACTTACTAGTCTCCAGGCACGTGTCAGATATATACATCCTGT", 
            "601MF":    "CTGGAGAATCCCGGTGCCGAGGCCGCTCAATTGGTCGGGAGTAATCCCCTTGGCGGTTAAAACGCGGGGGACACCGCGTACGTGCGTTTAAGCGGTGCTAGAGCTGTCTACTAGTCTCCAGGCACGTGTCAGATATATACATCCTGT",
            "601L":     "CTGGAGAATCCCGGTGCCGAGGCCGCTCAATTGGTCGTAGACAGCTCTAGCACCGCTTAAACGCACGTACGCGCCGCGTACGTGCGTTTAAGCGGTGCTAGAGCTGTCTACGACCAATTGAGCGGCCTCGGCACCGGGATTCTCCAG",
            "5S":       "CTTCCAGGGATTTATAAGCCGATGACGTCATAACATCCCTGACCCTTTAAATAGCTTAACTTTCATCAAGCAAGAGCCTACGACCATACCATGCTGAATATACCGGTTCTCGTCCGATCACCGAAGTCAAGCAGCATAGGGCTCGGT"  }

@dataclass
class Parameters:
    KRESCFACTOR: float
    STYLE: str = "b_index" # "b_index" or "open_sites" or "ph_index"
    LENGTH: int = 14 # 28 for ph_index, 14 for b_index 
    SEQUENCE_LENGTH: int = 147
    nucmethod: str = "hybrid"
    freedna_method: Optional[str] = None 
    FOR_DNA_HISTONE:bool = False ## if you use ph_index, set this to True because it saves the data in the dna_histone folder, otherwise it saves in the nucbreathfe folder

    FLIP_SEQUENCE: bool = False ### Flip is only required for the DNA histone energies i.e FOR_DNA_HISTONE=TRUE
    HARD_CONS: bool = False


MAX_WORKERS = 5